name: dbt_oulad
version: 1.0.0
config-version: 2

profile: dbt_oulad

model-paths: ["models"]
test-paths: ["tests"]

models:
  dbt_oulad:
    staging:
      +schema: stg
      +materialized: view
    intermediate:
      +schema: int
      +materialized: view
    marts:
      +schema: mart
      +materialized: table
